/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://rkvc45x7w5b2nkv5l3ytrnq5pi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6kj2obf4evcy5i6f2e5wcgks3a",
    "aws_cognito_identity_pool_id": "us-east-1:d3891c9d-0ad2-4b05-aef2-4fdec417483a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vgqFGQv5V",
    "aws_user_pools_web_client_id": "k9khne03upol3fnqcrdt7c61u",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "foodlemaps6f66029150134e6d98beb722debb55bf161550-foodlemaps",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
